// Applications
export const APPS_LOADED = 'APPS_LOADED';
export const APP_LOADED = 'APP_LOADED';
export const APP_DELETED = 'APP_DELETED';

// Services
export const SERVICES_LOADED = 'SERVICES_LOADED';
export const SERVICE_LOADED = 'SERVICE_LOADED';
export const SERVICE_REMOVED = 'SERVICE_REMOVED';

// Signin
export const SIGNED_IN = 'SIGNED_IN';
export const ERROR_SIGINIG_IN = 'ERROR_SIGINIG_IN';
export const SAVE_CURRENT_PATH = 'SAVE_CURRENT_PATH';
export const UNAUTHORIZED = 'UNAUTHORIZED';

// Notifications
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_NOTIFICATION_OBJECT = 'ADD_NOTIFICATION_OBJECT';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
